### ISSUE TITLE
Plotting for ShinyGO ORA results

### ISSUE THREAD

**Issue by Natpod** [GangLiLab/genekitr#12] opened 2023-04-25 12:10 UTC
**Describe the bug**
Hello, I am attempting to perform a GO term visualization of my ShinyGO ORA results with plotEnrich. There are GO terms that plotEnrich won't recognize, is there a way to skip them entirely? thank you

**Comment by reedliu** [comment] 2023-04-26 00:19
Hi, could you send me the ShinyGO ORA results first? So I could reproduce the test.

**Comment by Natpod** [comment] 2023-04-26 10:48
Sure, here are the first 100 rows to my shinygo dataset. As you can see, if you manually remove the unrecognized GO codes, the plotEnrichment works fine

thank you once again for your feedback

Regards,
Natalia García Sánchez

Enviado desde Outlook<http://aka.ms/weboutlook>
________________________________
De: Yunze Liu ***@***.***>
Enviado: miércoles, 26 de abril de 2023 2:20
Para: GangLiLab/genekitr ***@***.***>
Cc: NataliaGarciaBC ***@***.***>; Author ***@***.***>
Asunto: Re: [GangLiLab/genekitr] [shiny-bug] (Issue #12)


Hi, could you send me the ShinyGO ORA results first? So I could reproduce the test.

**Comment by reedliu** [comment] 2023-04-28 23:10
Hi, I didn't see the example dataset. Have you uploaded the file successfully? Maybe you could save it as .rda and then upload it.

**Comment by reedliu** [comment] 2023-05-13 06:58
@Natpod I still need additional information to follow-up on this issue. Please let me know if you are still experiencing it or were able to resolve it on your own. If not hear back in the next week or so, I'll be closing the report. Thanks.

**Comment by Natpod** [comment] 2023-05-16 09:51
Hi,

I am sending you the first 30 rows via email, I am unaware if you are receiving this information. In any case, please contact me if this happens.

Regards,

Natalia García Sánchez

Enviado desde Outlook<http://aka.ms/weboutlook>
________________________________
De: Yunze Liu ***@***.***>
Enviado: sábado, 13 de mayo de 2023 8:59
Para: GangLiLab/genekitr ***@***.***>
Cc: NataliaGarciaBC ***@***.***>; Mention ***@***.***>
Asunto: Re: [GangLiLab/genekitr] Plotting for ShinyGO ORA results (Issue #12)


@Natpod<https://github.com/Natpod> I still need additional information to follow-up on this issue. Please let me know if you are still experiencing it or were able to resolve it on your own. If not hear back in the next week or so, I'll be closing the report. Thanks.

**Comment by Natpod** [comment] 2023-05-16 09:53
[reprex_shinyGO_data_issue.csv](https://github.com/GangLiLab/genekitr/files/11486383/reprex_shinyGO_data_issue.csv)
Hi, can you access the file now?

Thank you

**Comment by reedliu** [comment] 2023-05-19 23:25
Is this file from ShinyGO the original one? If so, it appears to be incorrect as it uses the same value for Fold Enrichment as qvalue, whereas the correct formula for Fold Enrichment is GeneRatio divided by BgRatio.

![image](https://github.com/GangLiLab/genekitr/assets/34302878/2a0cb7cd-ef49-40f4-8e31-fcf6762be1b7)

**Comment by reedliu** [comment] 2023-05-19 23:44
If it is not, please upload the original result from ShinyGO and I will try to write a function to import its result and link to the plotEnrich function.

**Comment by Natpod** [comment] 2023-05-20 18:16
Okey, thank you for the patience and the fast response! 
[reprex_ShinyGO_result.xlsx](https://github.com/GangLiLab/genekitr/files/11522925/reprex_ShinyGO_result.xlsx)

this is my ShinyGO output

**Comment by reedliu** [comment] 2023-05-21 03:17
Update a function `importShinygo` in version >= 1.2.1

Due to the limited information of shinyGO output, only FDR is provided, and then only FoldEnrich and nGenes, pathway genes (these two can be used to calculate RichFactor).

Anyway, you could select and modify the interested terms in enrich furthur.

Also, you could change other plotting parameters following `plotEnrich` manual, such as color, text size, line etc.

> options for plot_type: dot/bar/bubble/lollipop/wordcloud
options for term_metric: "RichFactor"/"FoldEnrich"


enrich = importShinygo('reprex_ShinyGO_result.xlsx')
demo = enrich[1:10,]
plotEnrich(demo, plot_type = "dot",stats_metric = 'qvalue',term_metric = 'FoldEnrich',scale_ratio = 0.1)
plotEnrich(demo, plot_type = "bar",stats_metric = 'qvalue',term_metric = 'RichFactor',scale_ratio = 0.1)
plotEnrich(demo, plot_type = "bubble",stats_metric = 'qvalue',scale_ratio = 0.1)
plotEnrich(demo, plot_type = "wordcloud",stats_metric = 'qvalue')

![image](https://github.com/GangLiLab/genekitr/assets/34302878/e7f24574-e33d-4e1a-906a-8aed4259e167)

**Comment by Natpod** [comment] 2023-05-22 08:28
Wonderful, thank you!

**Closed as completed** 2023-05-22 09:46 UTC
Labels: plot, enrichment

**Comment by Natpod** [comment] 2023-05-27 13:37
hello, it seems that after import i cannot plot the hierarchy map from enriched categories
```
enrichplot::plotEnrich(enrich, plot_type = "gomap", term_metric = "FoldEnrich", stats_metric="qvalue", up_color = '#a32a31',down_color = '#3665a6', ont="BP", org="bna")
```

the problem is in the get_ancestor_data function with returns the following traceback:
```
Error in get_ancestor_data(enrich_df, ont = NULL) : 
Please give ontology to "ont" from "BP","CC" and "MF"
```
